updated README
hiqdev/nginx-proxy-common pull request #1
Opened 2021-07-05 09:33 UTC by Drakorgaur

2021-07-06 07:08 UTC, strorch commented on README.md
> +To setup new proxy for 127.0.0.2 - `python3 nginx-proxy-common setup 127.0.0.2`
```suggestion
To setup new proxy for 127.0.0.2 - `./nginx-proxy-common setup 127.0.0.2`
```

`nginx-proxy-common` - це екзекютабл файл

2021-07-06 07:08 UTC, strorch commented on README.md
> +To setup new proxy for 127.0.0.2 - `python3 nginx-proxy-common setup 127.0.0.2`
@hiqsol

2021-07-07 09:26 UTC, strorch approved these changes

2021-07-07 10:21 UTC, hiqsol requested changes

2021-07-07 10:21 UTC, hiqsol commented on README.md
> +To start service(in fresh-created directory) - `docker-compose up -d`
лучше тоже делать через саму комманду:
```suggestion
To start service(in fresh-created directory) - `./nginx-proxy-common start 127.0.0.2`
```

2021-07-07 10:47 UTC, strorch commented on README.md
> +To start service(in fresh-created directory) - `docker-compose up -d`
марк каже, що так не працює

![image](https://user-images.githubusercontent.com/23340907/124746561-b0ee6a00-df29-11eb-9149-021c2bd0ae40.png)

2021-07-15 08:04 UTC, hiqsol approved these changes

2021-07-15 08:04 UTC, merged